Mafia-Hands/Mafia

CODE_OF_CONDUCT.md
=> Create CODE_OF_CONDUCT.md 

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation_request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
This PR fixes #4 
Add templates for creating issues / pull requests, you can test out the template by creating a test issue / test PR in my personal fork: [https://github.com/LindaBot/Mafia](https://github.com/LindaBot/Mafia)
Added Issues Templates: 
* New Feature Request
* Bug Report
* Documentation Request
Added Pull Request Template
(Delete the ones that are not relevant)
* If new documentation is …
=> Create  issues template

backend/.gitignore, backend/index.js, backend/package-lock.json, backend/package.json
Closes #19
Implemented a basic socket.io server that is mounted on an express server.
Currently it just accepts socket.io connections, and logs a message to the console whenever a client connects.
The server is currently configured through CORS to only accept connections from `http://localhost:3000` (the default origin for create-react-app). These settings should be updated as we get closer to production.
=> Backend Server Skeleton Code

.github/ISSUE_TEMPLATE/new-backend-feature.md
This PR fixes #50 
Please include a summary of the changes here.
Added a markdown file called new-backend-feature.md which describes the issue template for backend features
* This change requires a documentation update - Documentation issue number #50 
* Have you merged main into your branch? *Yes*
* Have you tested your changes to ensure it works as expected and does not break existing functionality? *Yes*
* If applicable, please ensure sufficient tests are added that is related to the changes. *NA*
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project` *Done*
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed? *Yes*
=> Adding an issue template for backend feature requests

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation_request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/new-frontend-feature.md
Modify Issue Templates to add an approval checkbox at the bottom of each created issue.
Newly created issues will need to be approved by one other developer before it can be assigned and work on it can begin.
This PR fixes #43 
Please include a summary of the changes here.
=> Add Issue Approvals

frontend/src/App.js, frontend/src/Components/CodeJoinBar.jsx, frontend/src/Components/CreateGame.jsx, frontend/src/Components/NicknameBar.jsx
This PR fixes #25 
Add components for Nickname field, Game Code Field, Create Game field
Lobby Setting button will be added when the Setting Screen field is created 
=> Home screen

frontend/package-lock.json, frontend/package.json, frontend/src/Components/Player.jsx, frontend/src/Components/Table.jsx, frontend/src/Styles/Player.module.css, frontend/yarn.lock
This PR fixes #29
- Added styling for hovering, red button (for indicating if player has voted), dead, clicked
- Added a bit of validation for the onclick 
- Added classNames library for a bit easier way of adding conditional styles.
There is no logic implemented here and everything is passed in as props. This component will need to be looked at after the socket io has been implemented. 
(Please include screenshots/GIF here if applicable)
Hover
Clicked
Voted (This requires player to be on table)
=> Added styling for player

frontend/src/Components/Timer.jsx
This PR fixes #30 
Created the countdown timer component 
Timer can be used as 'Timer(xx)-> xx is the total second  the timer needs to run'
The time left will be display as 'minute : second' 
A button is created to control when to start or pause the timer
Further css/layout/content improvement is required.
* If new documentation is required for this change, have you created a new documentation issue that …
=> #30 Create Timer

backend/Events/GameStartEvents.js, backend/config.json, backend/domain/DTO/response/GameStartDTO.js, backend/domain/Enum/Role.js, backend/index.js
This PR fixes #107 
Please include a summary of the changes here.
- Added an event handler to process start-game events
- Changed the Role enum to store the string representation of the role
- Added a DTO class to abstract the JSON object returned for the start-game event
- Updated the config file to store the role allocation logic values
- Updated index.js to redirect start-game events to the newly added handler
<br/>
Co-authored-by: @parfei 
Co-authored-by: @MKTPR
=> Added an event handler to process start-game events

backend/Events/GameStartEvents.js
This PR fixes #129 
- Replaced ceil() with Math.ceil() to correctly call the ceil function
- Also changed the logic to add multiple occurrences of a role to an array in getAvailableRolesToAssign()
* Bug fix (Non-breaking change which fixes a bug)
=> Fixing logic and build errors in the start-game event handler

backend/Events/GameStateEvents/NightStateChangeEvents.js, backend/Events/GameStateEvents/StateChangeEvents.js, backend/Events/GameStateEvents/TrialStateChangeEvents.js, backend/Events/LobbyEvents.js, backend/domain/DTO/response/NightEndDTO.js, backend/domain/DTO/response/TrialEndDTO.js, backend/package.json, backend/test/NightStateChangeEvents.test.js, backend/test/mocks/MafiaGameMock.js, frontend/src/GameUtils.js, frontend/src/Hooks/useGameState.js, frontend/src/Hooks/useLobbyState.js
This PR fixes #169 
- Added Timeout to call phase start events e.g. start day
- changed DTO's and trial/discussion event handling 
* Bug fix (Non-breaking change which fixes a bug)
=> Fixed Logic/Socket Issues 

frontend/src/Components/Player.jsx, frontend/src/Hooks/useGameState.js, frontend/src/Pages/GamePage.js, frontend/src/Socket.js, frontend/src/Styles/Player.module.css
This PR fixes #181
Added ability to show client who they have voted for. Both for night abilities and for day time trial vote.
Changed styling to colour the highlighted player
=> Added functionality to show who a player has voted for.

frontend/puppeteer/package-lock.json, frontend/src/Components/Table.jsx, frontend/src/Styles/Table.module.css
This PR fixes #114 
- Changed table to use context more easily
- Added functionality to move on trial players to center of table
After: [Insert Screenshot]
=> Moved on trial players to the center of table

frontend/src/Hooks/useGameState.js
This PR fixes #202 
- Reseted timeToVote 
- Updated status when trial is skipped
* Bug fix (Non-breaking change which fixes a bug)
=> fixed bug of timer not reseting

backend/config.json
This PR fixes #[Insert Issue Number]
Please include a summary of the changes here.
(Please include screenshots/GIF here if applicable)
Before: [Insert Screenshot]
After: [Insert Screenshot]
(Delete the ones that are not relevant)
* Bug fix (Non-breaking change which fixes a bug)
* Breaking change (This change would cause existing functionality to break)
* This change requires a documentation update - Documentation issue number #[Insert Issue Number]
* Please ensure this PR has a `label`, is linked …
=> Increase voting time

CODE_OF_CONDUCT.md
This PR fixes #6 
Adds CODE_OF_CONDUCT.md back into the root such that it is recognized by GitHub Communities tab.
=> Added code of conduct to root

README.md
This PR resolves #244 
Updating and cleaning up the README.md, the following sections have been done:
+Installation
+Usage
+Support
+Roadmap
And the following sections need @skyn310198 to finish up.
+Contributing
+Author and acknowledgment
+License
+Project status
Documentation
=> README.md clean up and expansion

backend/domain/Enum/GameStateEnum.js, backend/domain/Enum/Role.js, backend/domain/MafiaGame.js, backend/domain/Player.js, backend/domain/Room.js, backend/domain/VoteHandler.js
This PR closes #252 
Added JSDoc comments explaining the purposes of each class in the domain model.
Also added JSDoc comments for the key methods in each class.
Also replaced the existing comments for the enums with JSDoc.
No actual changes to any code. Just comments.
N/A
(Delete the ones that are not relevant)
* Documenting existing code
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation …
=> Commenting for domain objects

CONTRIBUTING.md
This PR fixes #257 
Documented the branch name tags to be used for testing work and refactoring
* This change requires a documentation update - Documentation issue number #257 
=> Added additional branch name tags to the contributing guidelines

CONTRIBUTING.md
This PR fixes https://github.com/Mafia-Hands/Mafia/issues/105
Added guidelines in `CONTRIBUTING` about:
*  PRs require 2+ reviewers
*  PR length
*  Link code conventions
* Commenting in the codebase
* Testing in the codebase
Documentation
=> PR, Commenting and Testing Modifications to CONTRIBUTING

backend/test/mocks/MafiaGameMock.js, backend/test/unit/NightStateChangeEvents.unit.test.js, backend/test/unit/TrialStateChangeEvents.unit.test.js
This PR fixes #276 and #278 
- Added comments to `TrialStateChangeEvents.unit.test` and `NightStateChangeEvents.unit.test` and `MafiaGameMock`
- Refactored the exports in `MafiaGameMock`
N/A
- Comments
- Refactoring
=> Commenting + minor refactoring to MafiaGameMock
